---
- name: Check role requirements
  include_tasks: includes/preflight.yml

- name: Ensure user and environment
  include_tasks: includes/prepare.yml

#- name: Check Bitwarden is already installed
#  ansible.builtin.stat:
#    path: "{{ bitwarden_install_dir }}"
#  register: output_dir

- name: Include Bitwarden setup
  include_tasks: includes/install.yml
  when: not output_dir.stat.exists

- name: Configure Bitwarden
  include_tasks: includes/configure.yml
