---
- name: Check role requirements
  include_tasks: includes/preflight.yml

- name: Ensure user and environment
  include_tasks: includes/prepare.yml

- name: Check Bitwarden is already installed
  ansible.builtin.stat:
    path: "{{ bitwarden_install_dir }}"
  register: output_dir

- name: Include Bitwarden setup
  include_tasks: includes/install.yml
  when: not output_dir.stat.exists

- name: Configure Bitwarden
  include_tasks: includes/configure.yml

- name: Update Bitwarden if required
  include_tasks: includes/update.yml

- name: Check Bitwarden is already running
  docker_container_info:
    name: bitwarden-nginx
  register: bw_running

- name: Ensure Bitwarden is started
  command: ./bitwarden.sh restart
  register: bw_start
  args:
    chdir: "{{ bitwarden_user_home }}"
  become_user: "{{ bitwarden_user }}"
  become: true
  when: "not bw_running.exists"
