---
- name: Check role requirements
  ansible.builtin.include_tasks: includes/preflight.yml

- name: Ensure user and environment
  ansible.builtin.include_tasks: includes/prepare.yml

- name: Check Bitwarden is already installed
  ansible.builtin.stat:
    path: "{{ bitwarden_install_dir }}"
  register: output_dir

- name: Include Bitwarden setup
  ansible.builtin.include_tasks: includes/install.yml
  when: not output_dir.stat.exists or bitwarden_test_install_script

- name: Configure Bitwarden
  ansible.builtin.include_tasks: includes/configure.yml
