- name: Copy Bitwarden nginx certificate in place
  copy:
    src: "{{ bitwarden_nginx_cert_path }}"
    dest: "{{ bitwarden_install_dir }}/ssl/bitwarden.crt"
    remote_src: true
    owner: "{{ bitwarden_user }}"
    group: "{{ bitwarden_group }}"
    mode: "0600"

- name: Copy Bitwarden nginx key in place
  copy:
    src: "{{ bitwarden_nginx_key_path }}"
    dest: "{{ bitwarden_install_dir }}/ssl/bitwarden.key"
    remote_src: true
    owner: "{{ bitwarden_user }}"
    group: "{{ bitwarden_group }}"
    mode: "0600"

- name: Ensure values in Bitwarden configuration file
  ansible.builtin.lineinfile:
    path: "{{ bitwarden_install_dir }}/config.yml"
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}: {{ item.value }}"
  loop:
    - key: "url"
      value: "https://{{ bitwarden_domain_name }}"
    - key: "ssl"
      value: "true"
    - key: ssl_certificate_path
      value: "/etc/ssl/bitwarden.crt"
    - key: "ssl_key_path"
      value: "/etc/ssl/bitwarden.key"
  register: bitwarden_config
  notify: restart bitwarden

- name: Run Bitwarden setup container in update mode
  docker_container:
    image: bitwarden/setup
    name: bw-setup
    detach: false
    volumes:
      - "{{ bitwarden_install_dir }}:/bitwarden"
    env_file: "{{ bitwarden_install_dir }}/env/uid.env"
    command:
      - dotnet
      - Setup.dll
      - "-update 1"
      - "-os lin"
      - "-corev {{ bitwarden_docker_image_coreversion }}"
      - "-webv {{ bitwarden_docker_image_webversion }}"
  register: bitwarden_update
  notify: restart bitwarden
  when: bitwarden_config.changed # noqa no-handler

- name: Debug Bitwarden update
  debug:
    var: bitwarden_update
    verbosity: 1

- name: Ensure Bitwarden global environment
  ansible.builtin.lineinfile:
    path: "{{ bitwarden_install_dir }}/env/global.override.env"
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ bitwarden_global_env | dict2items }}"
  no_log: true
  notify: restart bitwarden
