- name: Download bitwarden.sh for {{ bitwarden_version }}
  get_url:
    url: https://raw.githubusercontent.com/bitwarden/server/v{{ bitwarden_version }}/scripts/bitwarden.sh
    dest: "{{ bitwarden_user_home }}/bitwarden.sh"
    mode: "0700"
    owner: "{{ bitwarden_user }}"
    group: "{{ bitwarden_group }}"

- name: Run install bitwarden.sh
  expect:
    command: ./bitwarden.sh install
    responses:
      (?i).+domain name.+: "{{ bitwarden_domain_name }}"
      (?i).+Encrypt.+: "n"
      (?i).+database.+: "vault"
      (?i).+installation id.+: "{{ bitwarden_global_installation_id }}"
      (?i).+installation key.+: "{{ bitwarden_global_installation_key }}"
      (?i).+SSL certificate to use.+: "y"
      (?i).+trusted SSL certificate.+: "n"
    creates: bwdata/config.yml
  register: bw_install
  args:
    chdir: "{{ bitwarden_user_home }}"
  become_user: "{{ bitwarden_user }}"
  become: true

- name: Debug output
  debug:
    var: bw_install

- name: Check install command output
  assert:
    that: "'Installation complete' in bw_install.stdout"

- name: Create directory for ansible custom facts
  ansible.builtin.file:
    state: directory
    recurse: yes
    path: /etc/ansible/facts.d

- name: Put current Bitwarden version in file for later checks
  copy:
    dest: "/etc/ansible/facts.d/bitwarden.fact"
    content: |
      [bitwarden]
      version = 1.0.0
    mode: "0644"

- name: Re-read facts after adding custom fact
  ansible.builtin.setup:
    filter: ansible_local
