- name: Run install bitwarden.sh with SSL mode "{{ bitwarden_ssl_mode }}"
  ansible.builtin.expect:
    command: ./bitwarden.sh install
    responses: "{{ bitwarden_install_inputs[bitwarden_ssl_mode] }}"
    timeout: 300
    creates: bwdata/config.yml
  register: bw_install
  args:
    chdir: "{{ bitwarden_user_home }}"
  become_user: "{{ bitwarden_user }}"
  become: true

- name: Debug output
  ansible.builtin.debug:
    var: bw_install
    verbosity: 1

- name: Check install command output
  ansible.builtin.assert:
    that: "'Installation complete' in bw_install.stdout"
