- name: Run install bitwarden.sh
  expect:
    command: ./bitwarden.sh install
    responses:
      (?i).+domain name.+: "{{ bitwarden_domain_name }}"
      (?i).+Encrypt.+: "n"
      (?i).+database.+: "vault"
      (?i).+installation id.+: "{{ bitwarden_global_installation_id }}"
      (?i).+installation key.+: "{{ bitwarden_global_installation_key }}"
      (?i).+SSL certificate to use.+: "y"
      (?i).+trusted SSL certificate.+: "n"
    creates: bwdata/config.yml
  register: bw_install
  args:
    chdir: "{{ bitwarden_user_home }}"
  become_user: "{{ bitwarden_user }}"
  become: true

- name: Debug output
  debug:
    var: bw_install
    verbosity: 1

- name: Check install command output
  assert:
    that: "'Installation complete' in bw_install.stdout"
