- name: Ensure bitwarden group
  ansible.builtin.group:
    name: "{{ bitwarden_group }}"
    state: present

- name: Ensure bitwarden user
  ansible.builtin.user:
    name: "{{ bitwarden_user }}"
    group: "{{ bitwarden_group }}"
    groups:
      - docker
    system: true
    home: "{{ bitwarden_user_home }}"
  register: user

- name: Download bitwarden.sh for {{ bitwarden_script_version }}
  when: not bitwarden_test_install_script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/bitwarden/self-host/{{ bitwarden_script_version }}/bitwarden.sh
    dest: "{{ bitwarden_user_home }}/bitwarden.sh"
    mode: "0700"
    owner: "{{ bitwarden_user }}"
    group: "{{ bitwarden_group }}"
  notify: update bitwarden # Notify update when Bitwarden install has changed
