- name: Ensure bitwarden group
  group:
    name: "{{ bitwarden_group }}"
    state: present

- name: Ensure bitwarden user
  user:
    name: "{{ bitwarden_user }}"
    group: "{{ bitwarden_group }}"
    groups:
      - docker
    system: true
    home: "{{ bitwarden_user_home }}"
  register: user