- name: Run Bitwarden update if required
  command: ./bitwarden.sh update
  register: bw_update
  args:
      chdir: "{{ bitwarden_user_home }}"
  become_user: "{{ bitwarden_user }}"
  become: true
  # Check if the current version from facts is lowe than the requested version
  when: bitwarden_version is version(ansible_local.bitwarden.bitwarden.version, operator='<', strict=True)

- name: Debug output
  debug:
      var: bw_update
