---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 3"

defaults:
  run:
    working-directory: "breuninger.bitwarden"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3.1.0
        with:
          path: "breuninger.bitwarden"

#      - name: "Free up disk space"
#        run: |
#          pwd
#          df -h
#          sudo apt-get -qq purge build-essential ghc*  azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel
#          sudo apt-get clean
#          docker system prune -af
#          sudo rm -rf /usr/local/*
#          df -h

      - name: Set up Python 3.
        uses: actions/setup-python@v4.4.0
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker pytest-testinfra ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
