---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 3"

defaults:
  run:
    working-directory: "breuninger.bitwarden"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: "Free up disk space"
        run: |
          sudo apt-get -qq purge build-essential ghc* 
          sudo apt-get clean
          docker system prune -af
          sudo mkdir /mnt/ccache
          mkdir ${{ env.CCACHE_DIR }}
          sudo mount --bind ${{ env.CCACHE_DIR }} /mnt/ccache
          sudo rm -rf /usr/local/*
          df -h

      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "breuninger.bitwarden"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker pytest-testinfra

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
